name: Sync MMRL submodule commit on main branch
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/sync_build_deploy.yml"
jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # needed to fetch all branches

      # Fetch the MMRL branch
      - run: |
          git fetch origin MMRL:MMRL
          git checkout MMRL

      # Merge/rebase into main or whatever you need
      - run: |
          git checkout main
          git merge MMRL --no-ff -m "Merge MMRL branch"
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git push origin main
