name: Sync MMRL branch commit on main branch
on:
  workflow_dispatch:
  push:
    branches:
      - MMRL
  workflow_run:
    workflows: ["Sync all modules in the MMRL repo"]
    types:
      - completed
permissions:
  contents: write
jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
            ref: 'main'
            token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure git
        run: |
          git config user.name "UnaTried"
          git config user.email "uccchipofya@gmail.com"
      - run: |
          rm -rf MMRL
          git fetch origin MMRL
          git worktree add MMRL origin/MMRL
          git -C MMRL rm -f CNAME .github
      - run: |
          git add MMRL
          git commit -m "Sync MMRL branch" || echo "No changes to commit"
          git push origin main
