name: Sync MMRL branch commit on main branch
on:
  workflow_dispatch:
  push:
    branches:
      - MMRL
permissions:
  contents: write
jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
            ref: 'main'
            token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure git
        run: |
          git config user.name "UnaTried"
          git config user.email "uccchipofya@gmail.com"
      - run: |
          rm -rf MMRL
          mkdir MMRL
          git fetch origin MMRL
          git checkout origin/MMRL -- .
          mv ReadMe.md json modules MMRL/
          git rm CNAME || echo "no CNAME file"
      - run: |
          git add MMRL
          git commit -m "Sync MMRL branch"
          git push origin main
