name: sync-mmrl-submodule
on:
  push:
    branches:
      - MMRL
jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive
            token: ${{ secrets.GITHUB_TOKEN }}
      - run: git submodule update --remote MMRL
      - run: |
              git add MMRL
              git commit -m "Sync MMRL submodule" || exit 0
              git push origin main